#!/bin/bash

SLEEP=" Sleep"
LOGOUT=" Logout"
RESTART=" Reboot"
SHUTDOWN=" Shutdown"

list_icons() {
    echo $LOCK
    echo $SLEEP
    echo $LOGOUT
    echo $RESTART
    echo $SHUTDOWN
}

handle_option() {
    case "$1" in
        "$SLEEP")
            if $(rofi_confirm $SLEEP); then
                betterlockscreen -l blur &
                systemctl suspend
            fi
            ;;
        "$LOGOUT")
            if $(rofi_confirm $LOGOUT); then
                i3-msg exit
            fi
            ;;
        "$RESTART")
            if $(rofi_confirm $RESTART); then
                reboot
            fi
            ;;
        "$SHUTDOWN")
            if $(rofi_confirm $SHUTDOWN); then
                shutdown now
            fi
            ;;
    esac
}

SELECTION="$(list_icons | rofi -dmenu -theme menu)"
handle_option $SELECTION &
